name: BukkitPluginTemplate
main: nz.co.lolnet.BukkitPluginTemplate.BukkitPluginTemplate
version: ${project.version}
authors: [James Anderson]
commands:
  BukkitPluginTemplateCommand:
    description: some command
    usage: /<command> [option]
       
permissions:
  BukkitPluginTemplate.*:
    description: Gives access to all BukkitPluginTemplate commands
    default: op
    children:
      BukkitPluginTemplate.use: true
  BukkitPluginTemplate.use:
    description: Allows player to use the command /BukkitPluginTemplateCommand
    default: op